name: CD Test - build and upload to test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CD-TEST:
    runs-on: ubuntu-latest

    steps:
      - name: Print something
        run: echo "This is the CD workflow."

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install pip
          python -m pip install build

      - name: Get version number
        id: version_number
        run: |
          $REF="${{github.ref}}"
          $TAG=$REF.Replace("refs/tags/", "")
          echo "::set-output name=TAG::$TAG"

      - name: Build package
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish package to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_KEY }}
          repository_url: https://test.pypi.org/legacy/
