# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.7, 3.8, 3.9
        uses: actions/setup-python@v2
        with:
          python-version: [3.7, 3.8, 3.9]

      - name: Install dependencies
        run: |
          python38 -m pip install --upgrade pip
          python38 -m pip install black isort tox

      - name: black check
        run: |
          python38 -m black --check .

      - name: isort check
        run: |
          python38 -m isort --profile black --check .

      - name: tox
        run: |
          python38 -m tox -r
