name: Just for testing
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-check:
    # If ref is not a tag, set 'test'
    if: ${{ startsWith(github.ref, 'refs/heads/') }}
    runs-on: ubuntu-latest

    steps:
      - name: version_number
        run: echo "::set-output name=TAG::$TAG"
        env:
          TAG: github['sha']

  deploy:
    needs: test-check
    runs-on: ubuntu-latest

    steps:
      - name: Print something
        run: echo "This is the CD workflow."

      - name: Print tag
        env:
          VERSION: needs.test-check.version_number.TAG
        run: echo "Version set to $VERSION"

      - name: Check reference
        env:
          REF: "${{github.ref}}"
        run: echo "Ref is $REF"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"