name: My workflow test

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  MY:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Hello World!"
          echo "This is a test.!"
