name: My workflow test

on:
  workflow_dispatch:
    branches: dst-43-cd-github-actions

jobs:
  MY:
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install pip
          python -m pip install build
      - name: Print Hello
        run: |
          echo "Hello World"
